USE DATABASE METADATA_PLANNING;
USE SCHEMA EVIDENCE;

CREATE OR REPLACE FUNCTION NORMALIZE_ASSET_TYPE(atlan_type STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
  CASE
    WHEN atlan_type ILIKE 'Table' THEN 'TABLE'
    WHEN atlan_type ILIKE 'Column' THEN 'COLUMN'
    WHEN atlan_type ILIKE 'View' THEN 'VIEW'
    WHEN atlan_type ILIKE 'MaterialisedView' OR atlan_type ILIKE 'MaterializedView' THEN 'MATERIALIZED_VIEW'
    ELSE UPPER(COALESCE(atlan_type,'UNKNOWN'))
  END
$$;

CREATE OR REPLACE PROCEDURE POPULATE_ASSET_UNIVERSE_FROM_ATLAN_GOLD(CONNECTOR_FILTER STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  TRUNCATE TABLE EVIDENCE.ASSET_UNIVERSE;

  INSERT INTO EVIDENCE.ASSET_UNIVERSE(asset_key, asset_type, domain_key, use_case_key, is_active, updated_ts)
  SELECT
    a.ASSET_QUALIFIED_NAME,
    EVIDENCE.NORMALIZE_ASSET_TYPE(a.ASSET_TYPE),
    NULL, NULL,
    TRUE,
    CURRENT_TIMESTAMP()
  FROM atlan_gold.public.ASSETS a
  WHERE a.STATUS='ACTIVE'
    AND (CONNECTOR_FILTER IS NULL OR a.CONNECTOR_NAME = CONNECTOR_FILTER);

  RETURN 'OK: loaded ' || SQLROWCOUNT || ' assets';
END;
$$;

CREATE OR REPLACE PROCEDURE POPULATE_EVIDENCE_FROM_ATLAN_GOLD()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  DELETE FROM EVIDENCE.EVIDENCE_OBSERVATION WHERE source='ATLAN_GOLD';

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(ASSET_TYPE),
         'atlan.owner.exists', IFF(ARRAY_SIZE(OWNER_USERS)>0,TRUE,FALSE), 0.95
  FROM atlan_gold.public.ASSETS WHERE STATUS='ACTIVE';

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(ASSET_TYPE),
         'atlan.description.length', COALESCE(LENGTH(DESCRIPTION),0), 0.90
  FROM atlan_gold.public.ASSETS WHERE STATUS='ACTIVE';

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(ASSET_TYPE),
         'atlan.tags.count', COALESCE(ARRAY_SIZE(TAGS),0), 0.90
  FROM atlan_gold.public.ASSETS WHERE STATUS='ACTIVE';

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(ASSET_TYPE),
         'atlan.glossary.links.count', COALESCE(ARRAY_SIZE(TERM_GUIDS),0), 0.85
  FROM atlan_gold.public.ASSETS WHERE STATUS='ACTIVE';

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(ASSET_TYPE),
         'atlan.certification.present', IFF(CERTIFICATE_STATUS IS NOT NULL AND CERTIFICATE_STATUS<>'',TRUE,FALSE), 0.90
  FROM atlan_gold.public.ASSETS WHERE STATUS='ACTIVE';

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(ASSET_TYPE),
         'atlan.readme.present', IFF(README_GUID IS NOT NULL AND README_GUID<>'',TRUE,FALSE), 0.90
  FROM atlan_gold.public.ASSETS WHERE STATUS='ACTIVE';

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(ASSET_TYPE),
         'atlan.has_lineage', COALESCE(HAS_LINEAGE,FALSE), 0.95
  FROM atlan_gold.public.ASSETS WHERE STATUS='ACTIVE';

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(ASSET_TYPE),
         'atlan.lineage.freshness.days', DATEDIFF('day', TO_TIMESTAMP_NTZ(UPDATED_AT/1000), CURRENT_TIMESTAMP()), 0.60
  FROM atlan_gold.public.ASSETS
  WHERE STATUS='ACTIVE' AND HAS_LINEAGE=TRUE AND UPDATED_AT IS NOT NULL;

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',a.ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(a.ASSET_TYPE),
         'atlan.custom_metadata.present', TRUE, 0.90
  FROM atlan_gold.public.CUSTOM_METADATA cm
  JOIN atlan_gold.public.ASSETS a ON a.GUID=cm.ASSET_GUID
  WHERE a.STATUS='ACTIVE' AND cm.STATUS='active'
  GROUP BY 1,2,3,4,5,6,7;

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',a.ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(a.ASSET_TYPE),
         'atlan.policy.linked.exists', TRUE, 0.55
  FROM atlan_gold.public.CUSTOM_METADATA cm
  JOIN atlan_gold.public.ASSETS a ON a.GUID=cm.ASSET_GUID
  WHERE a.STATUS='ACTIVE' AND cm.STATUS='active'
    AND (cm.CUSTOM_METADATA_NAME ILIKE '%policy%' OR cm.ATTRIBUTE_NAME ILIKE '%policy%')
  GROUP BY 1,2,3,4,5,6,7;

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(ASSET_TYPE),
         'atlan.steward.exists', IFF(ARRAY_SIZE(OWNER_USERS)>0,TRUE,FALSE), 0.70
  FROM atlan_gold.public.ASSETS WHERE STATUS='ACTIVE';

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',a.ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(a.ASSET_TYPE),
         'atlan.classification.pii', TRUE, 0.70
  FROM atlan_gold.public.TAGS t
  JOIN atlan_gold.public.ASSETS a ON a.GUID=t.ASSET_GUID
  WHERE a.STATUS='ACTIVE'
    AND (t.TAG_NAME ILIKE '%PII%' OR t.TAG_NAME ILIKE '%SENSITIVE%')
  GROUP BY 1,2,3,4,5,6,7;

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  WITH pii_cols AS (
    SELECT DISTINCT ASSET_GUID AS column_guid
    FROM atlan_gold.public.TAGS
    WHERE ASSET_TYPE='Column' AND (TAG_NAME ILIKE '%PII%' OR TAG_NAME ILIKE '%SENSITIVE%')
  ),
  table_cols AS (
    SELECT rad.GUID AS table_guid, f.VALUE::STRING AS column_guid
    FROM atlan_gold.public.RELATIONAL_ASSET_DETAILS rad,
         LATERAL FLATTEN(INPUT => rad.TABLE_COLUMNS) f
    WHERE rad.ASSET_TYPE='Table'
  )
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',a_table.ASSET_QUALIFIED_NAME,'TABLE',
         'atlan.pii.columns.count', COUNT(DISTINCT tc.column_guid), 0.80
  FROM table_cols tc
  JOIN pii_cols pc ON pc.column_guid=tc.column_guid
  JOIN atlan_gold.public.ASSETS a_table ON a_table.GUID=tc.table_guid
  WHERE a_table.STATUS='ACTIVE'
  GROUP BY 1,2,3,4,5,7;

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',a_start.ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(l.START_TYPE),
         'atlan.lineage.upstream.count', COUNT(DISTINCT l.RELATED_GUID), 0.90
  FROM atlan_gold.public.LINEAGE l
  JOIN atlan_gold.public.ASSETS a_start ON a_start.GUID=l.START_GUID
  WHERE l.DIRECTION='UPSTREAM' AND l.LEVEL=1 AND a_start.STATUS='ACTIVE'
  GROUP BY 1,2,3,4,5,7;

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',a_start.ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(l.START_TYPE),
         'atlan.lineage.downstream.count', COUNT(DISTINCT l.RELATED_GUID), 0.90
  FROM atlan_gold.public.LINEAGE l
  JOIN atlan_gold.public.ASSETS a_start ON a_start.GUID=l.START_GUID
  WHERE l.DIRECTION='DOWNSTREAM' AND l.LEVEL=1 AND a_start.STATUS='ACTIVE'
  GROUP BY 1,2,3,4,5,7;

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  WITH direct_edges AS (
    SELECT START_GUID, COUNT(DISTINCT RELATED_GUID) AS edge_cnt
    FROM atlan_gold.public.LINEAGE
    WHERE LEVEL=1
    GROUP BY START_GUID
  )
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',a.ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(a.ASSET_TYPE),
         'atlan.relationships.count', COALESCE(d.edge_cnt,0), 0.75
  FROM atlan_gold.public.ASSETS a
  LEFT JOIN direct_edges d ON d.START_GUID=a.GUID
  WHERE a.STATUS='ACTIVE';

  INSERT INTO EVIDENCE.EVIDENCE_OBSERVATION
  SELECT CURRENT_TIMESTAMP(),'ATLAN_GOLD',a.ASSET_QUALIFIED_NAME,NORMALIZE_ASSET_TYPE(a.ASSET_TYPE),
         'atlan.lineage.job.count',
         COALESCE(ARRAY_SIZE(p.INPUT_GUIDS_TO_PROCESSES),0)+COALESCE(ARRAY_SIZE(p.OUTPUT_GUIDS_FROM_PROCESSES),0),
         0.80
  FROM atlan_gold.public.PIPELINE_DETAILS p
  JOIN atlan_gold.public.ASSETS a ON a.GUID=p.GUID
  WHERE a.STATUS='ACTIVE';

  RETURN 'OK: loaded ATLAN_GOLD evidence';
END;
$$;

CREATE OR REPLACE PROCEDURE REFRESH_FROM_ATLAN_GOLD(CONNECTOR_FILTER STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  CALL EVIDENCE.POPULATE_ASSET_UNIVERSE_FROM_ATLAN_GOLD(CONNECTOR_FILTER);
  CALL EVIDENCE.POPULATE_EVIDENCE_FROM_ATLAN_GOLD();
  RETURN 'OK: refreshed ATLAN_GOLD';
END;
$$;
