USE DATABASE METADATA_PLANNING;

CALL EVIDENCE.REFRESH_FROM_ATLAN_GOLD('snowflake');
CALL EVIDENCE.REFRESH_FROM_SNOWFLAKE_ACCOUNT_USAGE();

CALL SCORE.RUN_ALL_ACTIVE_TEMPLATES('daily_atlan_gold_plus_snowflake');

SELECT * FROM SCORE.TEMPLATE_CATALOG ORDER BY template_id;

SELECT * FROM SCORE.ASSESSMENT_RESULT
ORDER BY created_ts DESC
LIMIT 200;

SELECT * FROM SCORE.EVIDENCE_GAP_REPORT;

SELECT evidence_key, source, COUNT(*) AS rows
FROM EVIDENCE.EVIDENCE_OBSERVATION
GROUP BY 1,2
ORDER BY 1,2;

SELECT evidence_value, COUNT(*) AS row_count
FROM EVIDENCE.EVIDENCE_OBSERVATION
WHERE evidence_key='snowflake.masking.present' AND source='SNOWFLAKE_ACCOUNT_USAGE'
GROUP BY 1
ORDER BY 2 DESC;
